# Numpyのインポート

In [1]:
# Numpyモジュールをインポート
import numpy as np

# Numpyの配列

In [2]:
# リストからNumPyの配列を作成
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [3]:
# 2重のリストからNumPyの2次元配列を作成
a = np.array([[0, 1, 2], 
              [3, 4, 5]])
print(a.shape)

(2, 3)


In [40]:
# 3重のリストからNumPyの3次元配列を作成
a = np.array([[[0, 1, 2, 3], 
               [4, 5, 6, 7], 
               [8, 9, 10, 11]],
                  
              [[12, 13, 14, 15], 
               [16, 17, 18, 19], 
               [20, 21, 22, 23]]])

print(a.shape)

(2, 3, 4)


# 配列の作成

# 配列の演算

In [8]:
# 配列と数値の間で演算

a = np.array([[0, 1, 2], 
              [3, 4, 5]])  # 2次元配列

print(a + 3)  # 各要素に3を足す
print()
print(a * 3)  # 各要素に3をかける

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [12]:
# 配列同士の演算
# この場合は同じ位置の各要素同士で演算が行われる

b = np.array([[0, 1, 2], 
              [3, 4, 5]])  # 2次元配列

c = np.array([[2, 2, 2], 
              [3, 3, 3]])  # 2次元配列

print(b + c)
print()
print(b * c)

[[2 3 4]
 [6 7 8]]

[[ 0  2  4]
 [ 9 12 15]]


In [14]:
# ブロードキャストという機能により、特定の条件を満たしていれば形状の異なる配列同士でも演算が可能
# ブロードキャストの厳密なルールは少々複雑で、全て記述すると長くなってしまうので、今回は必要最小限の解説としました。

d = np.array([[1, 1],
              [2, 2]])  # 2次元配列

e = np.array([1, 2])    # 1次元配列

print(d + e)

[[2 3]
 [3 4]]


# 次元操作

In [32]:
a = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7], 
              [8, 9, 10, 11]])
print(a.shape)

(3, 4)


In [33]:
a = a.reshape(2, 6)
print(a.shape)

(2, 6)


In [34]:
a = a.reshape(4, -1)
print(a.shape)

(4, 3)


In [35]:
# eshapeの引数を-1にすることで、どのような形状の配列でも1次元配列に変換することが可能
a = a.reshape(-1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# インデックス

In [36]:
# 配列の各要素へのアクセスは、リストの場合と同様にインデックスを利用
# 一次元配列の場合、以下のように[ ]内にインデックスを指定することで、要素を取り出すことができる

a = np.array([0, 1, 2, 3, 4, 5])
print(a[2])

2


In [38]:
# 更新
a[2] = 9
print(a)

[0 1 9 3 4 5]


In [39]:
# 2次元配列の場合、要素を取り出す際にはインデックスを縦横で2つ指定します。
# ,（カンマ）区切りでインデックスを並べることも、インデックスを入れた[ ]を2つ並べることもできます。

# 2次元配列の場合
b = np.array([[0, 1, 2],
              [3, 4, 5]])

print(b[1, 2])  # b[1][2]と同じ

5


# 統計量計算

In [46]:
a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2次元配列

print('合計', np.sum(a))
print('平均', np.average(a))
print('最大', np.max(a))
print('最小', np.min(a))

合計 15
平均 2.5
最大 5
最小 0


In [48]:
# 引数にaxisを指定すると、特定の方向で演算を行うことができます。

b = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2次元配列

print('縦方向で合計', np.sum(a, axis=0))
print('横方向で合計', np.sum(a, axis=1))

縦方向で合計 [3 5 7]
横方向で合計 [ 3 12]
